name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  make_check:
    strategy:
      matrix:
        config: [
          # Add new configs here
          '',
          'OPENSSL_TAG=master',
          'WOLFSSL_TAG=master ',
          'WOLFSSL_TAG=master WOLFSSL_CONFIG_OPTS="--enable-aesni --enable-intelasm --enable-all-crypto --with-eccminsz=192 --with-max-ecc-bits=1024 --enable-opensslcoexist --enable-sha"',
          'WOLFSSL_TAG=master WOLFSSL_CONFIG_OPTS="--enable-aesni --enable-intelasm --enable-sp=yes,asm --enable-all-crypto --with-eccminsz=192 --with-max-ecc-bits=1024 --enable-opensslcoexist --enable-sha"',
          'OPENSSL_TAG=master WOLFSSL_TAG=master',
        ]
    name: make check
    runs-on: ubuntu-latest
    # This should be a safe limit for the tests to run.
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout wolfProvider

      - name: Test wolfProvider
        run: |
          ${{ matrix.config }} ./scripts/build-wolfprovider.sh
          make check

      - name: Print errors 
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
