name: Simple Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ]
#    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  make_check:
    strategy:
      matrix:
        config: [
          # WOLFSSL master fails rsa & ecc setup
          'WOLFSSL_TAG=master',
          'OPENSSL_TAG=master WOLFSSL_TAG=master',
          # v5.7.2-stable build works with rsa & ecc setup
          '',
          'WOLFSSL_CONFIG_OPTS="--enable-aesni --enable-intelasm --enable-all-crypto --with-eccminsz=192 --with-max-ecc-bits=1024 --enable-opensslcoexist --enable-sha"',
          'WOLFSSL_CONFIG_OPTS="--enable-aesni --enable-intelasm --enable-sp=yes,asm --enable-all-crypto --with-eccminsz=192 --with-max-ecc-bits=1024 --enable-opensslcoexist --enable-sha"',
        ]
    name: make check
    runs-on: ubuntu-latest
    # This should be a safe limit for the tests to run.
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Checkout wolfProvider

      - name: Speed wolfProvider
        run: |
          ${{ matrix.config }} ./scripts/build-wolfprovider.sh
